# -*- coding: utf-8 -*-
"""Introduction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QTmUih7YC3zvoEuQpqEZF_3_LFwlPdbi
"""

class Animal:
    def __init__(self, name):
        self.name = name

    def eat(self):
        print(f"{self.name} is eating.")

    def sleep(self):
        print(f"{self.name} is sleeping.")


class Dog(Animal):
    def bark(self):
        print(f"{self.name} is barking.")


class Cat(Animal):
    def meow(self):
        print(f"{self.name} is meowing.")

a1 = Animal("A1")
a1.eat()
a1.sleep()

c1 = Cat("c1")
c1.eat()
c1.meow()

d1 = Dog("d1")
d1.eat()
d1.bark()